import base64
import re
from pathlib import Path


def main() -> int:
    ghx_path = Path(r"d:\meryShadeLa\ShadeLA\public\gh\unnamedC.ghx")
    raw = ghx_path.read_bytes()
    encoding = "utf-8"
    try:
        xml = raw.decode(encoding)
    except UnicodeDecodeError:
        # Some .ghx files contain non-UTF8 bytes. latin-1 is a reversible 1:1 mapping.
        encoding = "latin-1"
        xml = raw.decode(encoding)

    bak_path = ghx_path.with_suffix(ghx_path.suffix + ".bak")
    if not bak_path.exists():
        bak_path.write_text(xml, encoding=encoding)

    xml = xml.replace("RH_IN:CITY_MESHES_JSON", "RH_IN:OSM_GEOJSON")
    xml = xml.replace("CITY_MESHES_JSON", "OSM_GEOJSON")

    script = (
        "import Rhino\n"
        "import json\n"
        "import math\n"
        "import os\n"
        "import urllib.request\n"
        "\n"
        "# INPUTS:\n"
        "# - OSM_GEOJSON (Text) optional: GeoJSON FeatureCollection string\n"
        "#\n"
        "# OUTPUTS:\n"
        "# - geo (List[Geometry]): curves + breps + meshes\n"
        "# - dbg (Text JSON with stats)\n"
        "\n"
        "EARTH_R = 6378137.0\n"
        "DEG2RAD = math.pi / 180.0\n"
        "\n"
        "def _coerce_str(v):\n"
        "    try:\n"
        "        if v is None:\n"
        "            return None\n"
        "        if isinstance(v, str):\n"
        "            s = v.strip()\n"
        "            return s if s else None\n"
        "        return str(v)\n"
        "    except Exception:\n"
        "        return None\n"
        "\n"
        "def _as_float(v):\n"
        "    try:\n"
        "        return float(v)\n"
        "    except Exception:\n"
        "        return None\n"
        "\n"
        "def _load_geojson_text(v):\n"
        "    s = _coerce_str(v)\n"
        "    if not s:\n"
        "        return None, None, 'empty'\n"
        "\n"
        "    if s.startswith('http://') or s.startswith('https://'):\n"
        "        try:\n"
        "            with urllib.request.urlopen(s) as resp:\n"
        "                b = resp.read()\n"
        "            try:\n"
        "                return b.decode('utf-8'), 'url', None\n"
        "            except Exception:\n"
        "                return b.decode('utf-8', errors='replace'), 'url', None\n"
        "        except Exception as e:\n"
        "            return None, 'url', 'url_read_error: ' + str(e)\n"
        "\n"
        "    try:\n"
        "        if os.path.exists(s) and os.path.isfile(s):\n"
        "            with open(s, 'r', encoding='utf-8') as f:\n"
        "                return f.read(), 'path', None\n"
        "    except Exception as e:\n"
        "        return None, 'path', 'file_read_error: ' + str(e)\n"
        "\n"
        "    return s, 'inline', None\n"
        "\n"
        "def _decode_feature_collection(v):\n"
        "    s, src, load_err = _load_geojson_text(v)\n"
        "    if load_err:\n"
        "        return None, (src or 'unknown'), load_err\n"
        "    if not s:\n"
        "        return None, (src or 'unknown'), 'empty'\n"
        "    try:\n"
        "        obj = json.loads(s)\n"
        "    except Exception as e:\n"
        "        return None, (src or 'unknown'), 'json_parse_error: ' + str(e)\n"
        "    if not isinstance(obj, dict):\n"
        "        return None, (src or 'unknown'), 'not_a_dict'\n"
        "    if obj.get('type') != 'FeatureCollection':\n"
        "        return None, (src or 'unknown'), 'not_feature_collection'\n"
        "    feats = obj.get('features', None)\n"
        "    if not isinstance(feats, list):\n"
        "        return None, (src or 'unknown'), 'features_not_list'\n"
        "    return feats, (src or 'unknown'), None\n"
        "\n"
        "def _iter_lonlat_coords(geom):\n"
        "    if not isinstance(geom, dict):\n"
        "        return\n"
        "    t = geom.get('type')\n"
        "    c = geom.get('coordinates')\n"
        "    if not t or c is None:\n"
        "        return\n"
        "    def walk(x):\n"
        "        if isinstance(x, (list, tuple)):\n"
        "            if len(x) >= 2 and isinstance(x[0], (int, float)) and isinstance(x[1], (int, float)):\n"
        "                yield (float(x[0]), float(x[1]))\n"
        "            else:\n"
        "                for it in x:\n"
        "                    for p in walk(it):\n"
        "                        yield p\n"
        "    for p in walk(c):\n"
        "        yield p\n"
        "\n"
        "def _lonlat_to_xy(lon, lat, lon0, lat0):\n"
        "    x = (lon - lon0) * DEG2RAD * EARTH_R * math.cos(lat0 * DEG2RAD)\n"
        "    y = (lat - lat0) * DEG2RAD * EARTH_R\n"
        "    return x, y\n"
        "\n"
        "def _coords_to_polyline(coords, lon0, lat0, z=0.0, close=False):\n"
        "    if not isinstance(coords, list) or len(coords) < 2:\n"
        "        return None\n"
        "    pts = []\n"
        "    for p in coords:\n"
        "        if not isinstance(p, (list, tuple)) or len(p) < 2:\n"
        "            continue\n"
        "        lon = _as_float(p[0])\n"
        "        lat = _as_float(p[1])\n"
        "        if lon is None or lat is None:\n"
        "            continue\n"
        "        x, y = _lonlat_to_xy(lon, lat, lon0, lat0)\n"
        "        pts.append(Rhino.Geometry.Point3d(x, y, float(z)))\n"
        "    if close and len(pts) >= 3:\n"
        "        if pts[0].DistanceTo(pts[-1]) > 1e-6:\n"
        "            pts.append(pts[0])\n"
        "    if len(pts) < 2:\n"
        "        return None\n"
        "    pl = Rhino.Geometry.Polyline(pts)\n"
        "    return pl.ToNurbsCurve()\n"
        "\n"
        "def _get_height_m(props):\n"
        "    if not isinstance(props, dict):\n"
        "        return 0.0\n"
        "    h = props.get('height')\n"
        "    if h is not None:\n"
        "        try:\n"
        "            return max(0.0, float(str(h).replace('m','').strip()))\n"
        "        except Exception:\n"
        "            pass\n"
        "    levels = props.get('building:levels') or props.get('levels')\n"
        "    if levels is not None:\n"
        "        try:\n"
        "            lv = float(str(levels).strip())\n"
        "            if lv > 0:\n"
        "                return lv * 3.0\n"
        "        except Exception:\n"
        "            pass\n"
        "    return 0.0\n"
        "\n"
        "def _extrude_curve_to_brep(crv, height):\n"
        "    try:\n"
        "        if crv is None or height is None or height <= 0:\n"
        "            return None\n"
        "        if not crv.IsClosed:\n"
        "            return None\n"
        "        ext = Rhino.Geometry.Extrusion.Create(crv, float(height), True)\n"
        "        if ext is None:\n"
        "            return None\n"
        "        return ext.ToBrep()\n"
        "    except Exception:\n"
        "        return None\n"
        "\n"
        "def _brep_to_mesh(brep):\n"
        "    try:\n"
        "        if brep is None:\n"
        "            return None\n"
        "        mp = Rhino.Geometry.MeshingParameters.Default\n"
        "        meshes = Rhino.Geometry.Mesh.CreateFromBrep(brep, mp)\n"
        "        if not meshes:\n"
        "            return None\n"
        "        m = Rhino.Geometry.Mesh()\n"
        "        for mm in meshes:\n"
        "            if mm is not None:\n"
        "                m.Append(mm)\n"
        "        try:\n"
        "            m.Normals.ComputeNormals()\n"
        "            m.Compact()\n"
        "        except Exception:\n"
        "            pass\n"
        "        return m\n"
        "    except Exception:\n"
        "        return None\n"
        "\n"
        "try:\n"
        "    OSM_GEOJSON\n"
        "except NameError:\n"
        "    OSM_GEOJSON = None\n"
        "\n"
        "features, src, err = _decode_feature_collection(OSM_GEOJSON)\n"
        "\n"
        "lon0 = 0.0\n"
        "lat0 = 0.0\n"
        "coord_n = 0\n"
        "if isinstance(features, list):\n"
        "    for f in features:\n"
        "        if not isinstance(f, dict):\n"
        "            continue\n"
        "        g = f.get('geometry')\n"
        "        for lon, lat in _iter_lonlat_coords(g):\n"
        "            lon0 += lon\n"
        "            lat0 += lat\n"
        "            coord_n += 1\n"
        "if coord_n > 0:\n"
        "    lon0 /= float(coord_n)\n"
        "    lat0 /= float(coord_n)\n"
        "\n"
        "geom_counts = {}\n"
        "building_count = 0\n"
        "curve_count = 0\n"
        "brep_count = 0\n"
        "mesh_count = 0\n"
        "\n"
        "out = []\n"
        "if isinstance(features, list):\n"
        "    for f in features:\n"
        "        if not isinstance(f, dict):\n"
        "            continue\n"
        "        geom = f.get('geometry')\n"
        "        props = f.get('properties')\n"
        "        gtype = geom.get('type') if isinstance(geom, dict) else None\n"
        "        if isinstance(gtype, str) and gtype:\n"
        "            geom_counts[gtype] = geom_counts.get(gtype, 0) + 1\n"
        "        is_building = isinstance(props, dict) and (props.get('building') or props.get('building:part') or props.get('building:use'))\n"
        "        if is_building:\n"
        "            building_count += 1\n"
        "        h = _get_height_m(props)\n"
        "\n"
        "        try:\n"
        "            coords = geom.get('coordinates') if isinstance(geom, dict) else None\n"
        "            if gtype == 'LineString' and isinstance(coords, list):\n"
        "                crv = _coords_to_polyline(coords, lon0, lat0, 0.0, False)\n"
        "                if crv is not None:\n"
        "                    out.append(crv)\n"
        "                    curve_count += 1\n"
        "\n"
        "            elif gtype == 'Polygon' and isinstance(coords, list) and len(coords) > 0:\n"
        "                ring = coords[0] if isinstance(coords[0], list) else None\n"
        "                crv = _coords_to_polyline(ring, lon0, lat0, 0.0, True)\n"
        "                if crv is not None:\n"
        "                    out.append(crv)\n"
        "                    curve_count += 1\n"
        "                    if is_building and h > 0:\n"
        "                        brep = _extrude_curve_to_brep(crv, h)\n"
        "                        if brep is not None:\n"
        "                            out.append(brep)\n"
        "                            brep_count += 1\n"
        "                            m = _brep_to_mesh(brep)\n"
        "                            if m is not None:\n"
        "                                out.append(m)\n"
        "                                mesh_count += 1\n"
        "\n"
        "            elif gtype == 'MultiPolygon' and isinstance(coords, list):\n"
        "                for poly in coords:\n"
        "                    if not isinstance(poly, list) or len(poly) < 1:\n"
        "                        continue\n"
        "                    ring = poly[0] if isinstance(poly[0], list) else None\n"
        "                    crv = _coords_to_polyline(ring, lon0, lat0, 0.0, True)\n"
        "                    if crv is None:\n"
        "                        continue\n"
        "                    out.append(crv)\n"
        "                    curve_count += 1\n"
        "                    if is_building and h > 0:\n"
        "                        brep = _extrude_curve_to_brep(crv, h)\n"
        "                        if brep is not None:\n"
        "                            out.append(brep)\n"
        "                            brep_count += 1\n"
        "                            m = _brep_to_mesh(brep)\n"
        "                            if m is not None:\n"
        "                                out.append(m)\n"
        "                                mesh_count += 1\n"
        "        except Exception:\n"
        "            pass\n"
        "\n"
        "geo = out\n"
        "dbg = json.dumps({\n"
        "    'has_OSM_GEOJSON': OSM_GEOJSON is not None,\n"
        "    'source': src,\n"
        "    'feature_count': len(features) if isinstance(features, list) else 0,\n"
        "    'geometry_types': geom_counts,\n"
        "    'building_count': building_count,\n"
        "    'curve_count': curve_count,\n"
        "    'brep_count': brep_count,\n"
        "    'mesh_count': mesh_count,\n"
        "    'origin_lonlat': [lon0, lat0] if coord_n > 0 else None,\n"
        "    'err': err,\n"
        "}, ensure_ascii=False)\n"
    )

    b64 = base64.b64encode(script.encode("utf-8")).decode("ascii")

    # Replace only the first GhPython <chunk name="Script"> Text item.
    pat = re.compile(
        r"(<chunk name=\"Script\">.*?<item name=\"Text\" type_name=\"gh_string\" type_code=\"10\">)(.*?)(</item>)",
        re.S,
    )
    m = pat.search(xml)
    if not m:
        raise SystemExit("ERROR: embedded GhPython <item name=\"Text\"> not found")

    xml2 = xml[: m.start(2)] + b64 + xml[m.end(2) :]
    ghx_path.write_text(xml2, encoding=encoding)

    print("OK: patched", ghx_path)
    print("backup:", bak_path)
    print("script_bytes", len(script), "b64_len", len(b64))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
